[package]
name = "soviet_simulator"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.19.1"
bevy-inspector-egui = "0.37.0"
bevy_egui = "0.40"
bevy_hanabi = "0.19.0"
bevy_image_export = "0.17.0"
bevy_kira_audio = "0.26.0"
bevy_mod_outline = "0.13.0"
bevy_procedural_tree = "0.4.0"
bevy_rand = "0.15.2"
bevy_vector_shapes = "0.13.1"
kiddo = "6.0.2"
noiz = "0.5.0"
pathfinding = "4.15.0"
petgraph = "0.8.3"
postcard = { version = "1.1", features = ["use-std"] }
serde = { version = "1.0", features = ["derive"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
